name: CI

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse ECR Info
        id: ecr
        run: |
          ECR_URL="${{ secrets.AWS_ECR_REPO_URL }}"
          REGION="${{ secrets.AWS_REGION }}"

          echo "region=$REGION" >> $GITHUB_OUTPUT
          echo "url=$ECR_URL" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ steps.ecr.outputs.region }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image (No Push Yet)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ${{ steps.ecr.outputs.url }}:latest
            ${{ steps.ecr.outputs.url }}:${{ github.ref_name }}

      - name: Trivy Scan Image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ steps.ecr.outputs.url }}:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker Image (after passing scan)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.ecr.outputs.url }}:latest
            ${{ steps.ecr.outputs.url }}:${{ github.ref_name }}
